name: CI
on: [push, workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@omsu-ru"
      - name: Login to GitHub private NPM registry
        env:
          CI_ACCESS_TOKEN: ${{ secrets.@omsu/ci }}
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u "tr43om" -p "${CI_ACCESS_TOKEN}" -e "tr43om@gmail.com" -r "https://npm.pkg.github.com" -s "@omsu-ru"
      - name: Install deps and build
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
